namespace orphinel.LexorRuntime;

public enum TokenType
{
    SCRIPT_AREA, START_SCRIPT, END_SCRIPT,
    DECLARE, INT, CHAR, BOOL, FLOAT,
    IDENTIFIER,
    NUMBER,
    STRING,
    CHARACTER_LITERAL,
    BOOLEAN_TRUE, BOOLEAN_FALSE,
    ASSIGN,
    DOLLAR_SIGN,
    AMPERSAND,
    ESCAPE_CODE_OPEN_BRACKET, ESCAPE_CODE_CLOSED_BRACKET,
    ESCAPE_CODE,
    PARENTHESIS_OPEN, PARENTHESIS_CLOSE,
    MULTIPLY, DIVIDE, MODULO,
    PLUS, MINUS,
    GREATER_THAN, LESS_THAN,
    GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL,
    EQUALS, NOT_EQUALS,
    AND, OR, NOT,
    PRINT,
    SCAN,
    COLON,
    IF, START_IF, END_IF, ELSE, ELSE_IF,
    FOR, START_FOR, END_FOR, REPEAT_WHEN, START_REPEAT, END_REPEAT,
    COMMA,
    EOF
}
